---
- name: Looking for operatingsystem ID
  uri:
    url: "{{ satellite_registration_command_url }}/api/operatingsystems"
    user: "{{ satellite_registration_command_username }}"
    password: "{{ satellite_registration_command_password }}"
    force_basic_auth: "{{ satellite_registration_command_force_basic_auth }}"
    validate_certs: "{{ satellite_registration_command_validate_certs }}"
    method: "GET"
    body: "search=title=\"{{ satellite_registration_command_operatingsystem }}\""
    status_code: 200
  register: satellite_registration_command_operatingsystem_result
  when: satellite_registration_command_operatingsystem_id is not defined

- name: Checks if the operatingsystem was found 
  debug:
    msg: "This task fails if the operatingsystem was not found."
  failed_when: satellite_registration_command_operatingsystem_result.json.results | length == 0

- name: Set operatingsystem ID if exists
  set_fact:
    satellite_registration_command_operatingsystem_id: "{{ satellite_registration_command_operatingsystem_result.json.results[0].id }}"
  when: satellite_registration_command_operatingsystem_result.json.results | length > 0
